service: sqs

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

## permissions for SQS to send message
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:us-east-1:*:*"

# Lambda function with SQS Trigger
functions:
  sqsHello:
    handler: handler.sqshello
    memorySize: 128
    events:
      - sqs:
          arn: 
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 10

# SQS Queue
resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MyQueue"